version: '3'
services:
  radargui23:
    ##image: docker.io/natbodocker/radargui23:1.0
    image: radargui23:1.0
    ports:
      - 8038:8038

## -------------------------------------------------------------
## TODO See https://docs.docker.com/compose/startup-order/
## Compose does not wait until a container is “ready” (whatever that means for your particular application)
## - only until it’s running. There’s a good reason for this.
## The best solution is to perform this check in your application code,
## -------------------------------------------------------------
## docker-compose -f radargui23.yaml up
## docker-compose down

